#!/bin/sh
set -e

TAG=$1

if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi

SERVICES='
host
web
'

# #Build
docker build -f tools/dockerfile --pull .

for ITEM in $SERVICES; do 
  docker build -f tools/dockerfile -t ${ITEM}:${TAG} --target=${ITEM} -q .
	# docker build -f tools/dockerfile -t ${TAG} --target=${ITEM} -q .
done

# #Publish
# for ITEM in $SERVICES; do
#       docker push registry/silo/${ITEM}:${TAG}
# done