FROM mcr.microsoft.com/dotnet/core/sdk:3.1
COPY . /app
WORKDIR /app
RUN dotnet publish host/host.csproj -c Release -o dist
WORKDIR /app/dist
ENTRYPOINT ["./host"]

FROM mcr.microsoft.com/dotnet/core/sdk:3.1
COPY . /app
WORKDIR /app
RUN dotnet publish web/web.csproj -c Release -o dist
WORKDIR /app/dist
ENTRYPOINT ["./web"]